services:
  - type: web
    name: airsoft-shop
    env: python
    region: frankfurt
    plan: free
    buildCommand: "cd web_app && pip install -r requirements.txt"
    startCommand: "cd web_app && gunicorn --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false
